### ISSUE TITLE
Warnings about missing version informations when using ncurses+termlib

### ISSUE THREAD

**Issue by vvolkl** [key4hep/key4hep-spack#22]
Loading this library (dependency of ROOT et al.) results in constant warnings of:
```
/bin/bash: /cvmfs/sw.hsf.org/spackages/linux-ubuntu20.04-broadwell/gcc-9.3.0/ncurses-6.2-c5onutekmwbsn3rq2tjq3x5jj746xjtj/lib/libtinfo.so.6: no version information available (required by /bin/bash)
```
as far as I can tell this can be simply avoiding by using `ncurses~termlib`

**Comment by tmadlener** [comment]
Hi @vvokl,
I am seeing similar issues and this does seem to be a general `spack` problem. In most cases this can simply be ignored in my experience. However, in some cases this leads to crashes. For me e.g. when trying to start (the system installed) `gdb`. I have looked into this a bit more, but up until now I have mainly found what seems to be the source of the problem, but not a solution.

What is happening in the case above is that `bash` is looking for `libtinfo` at runtime to dynamically load it. It will then find the spack installed version before it finds the system version if a spack package depending on it is loaded. This is because spack will put itself on `LD_LIBRARY_PATH` before any system packages. The problem now is that the system version provides a `VERDEF` section in its binary, but the spack installed version does not. [See here for a bit more information](https://stackoverflow.com/a/38851073/3604607)

Just building `ncurses` from source (outside of spack) results in the same problem. So to me it looks like the system package is built slightly differently, such that the version information is embedded in the shared library. However, I have not yet found out how they are built and how this could be use to solve this issue in spack.

------ 
Another thing that I have used to get, e.g. `gdb` working again is to not do `spack load root` (or whatever pulls `libtinfo` in as dependency) but to just us the spack installed package, and set the path specifically to that (or in the case of root, simply do `source /path/to/spack/installed/root/bin/thisroot.sh`). With that everything works, but depending on the number of packages you want to load it can get tedious pretty quickly.

**Comment by vvolkl** [comment]
Hi @tmadlener,

I think even if spack provides a `VERDEF` section, it wouldn't be the one the system is looking for. For many applications, like running on batch, this actually is not an issue.

Using spack in a software development environment is stretching its intended purpose a bit, but it should definitely be possible.
In this case, I think you'll need to either commit to using more spack installed packages, or more system installed packages. In the first case you should install `gdb` with spack, and even `bash` if you want to get rid of the warnings. In the second case, you should take `ncurses` from the system.
Let me know if that works for you!

**Comment by tmadlener** [comment]
Hi @vvolkl,

> Using spack in a software development environment is stretching its intended purpose a bit, but it should definitely be possible.

Yes, I agree. In the end I think this issue is a nuisance that we have to live with when using spack to set up a development environment. At least for now there are one (and a half) viable workarounds listed in this:
1. Install everything in spack (including `bash` and `gdb` or other utilities that would normally used from system packages)
2. Use spack to install the software but then build your environment selectively from the installed packages. This somewhat defeats the purpose of spack in the first place, but if only one or two packages are involved it might be easier and faster to do this than to install a bunch of utility packages.

I think we need to at some point decide how to handle this when using spack for centrally installed software, where we should try to avoid such warnings. Building `ncurses~termlib` could be a workaround in that case, **if** `libtinfo` is installed on the system, because then `libtinfo` will be built as a part of `libncurses` and so, I suppose, the system `libtinfo` is loaded before the spack version.

**Comment by vvolkl** [comment]
`libtinfo` is  not a separate package on ubuntu, but also included as part of libncurses: https://bugs.launchpad.net/ubuntu/+source/ncurses/+bug/259139
 and `ncurses~termlib` conflicts with mesa (which is a dependency of root).

> This somewhat defeats the purpose of spack in the first place, but if only one or two packages are involved it might be easier and faster to do this than to install a bunch of utility packages.

For the purposes of deploying to an hpc, probably yes. For developing software, I think it can be a good compromise. It possibly invites all kinds of issues, but for certain system packages we can just check that it works. I think the spi group also still needs to decide if they will use hepos libs for spack installs.

**Comment by jmcarcell** [comment]
Closing stale issue, reopen if it appears again
