### ISSUE TITLE
Find better location for key4hep package base classes

### ISSUE THREAD

**Issue by hegner** [key4hep/key4hep-spack#268]
To get a better documentation for meta packages, the interface of the ilcsoftpackage needs to be completed. To reproduce one of the issues:

> $ spack info Ilcsoftpackage
> ==> Error: 'Ilcsoftpackage' object has no attribute 'build_system_class'

**Comment by vvolkl** [comment]
That's a valid point, but rather than completing it I think the code should be moved out of `packages/`. It's not really a meta-package (like `key4hep-stack`) but a Package Base class that would be located in a library directory (like `lib/spack/spack/build_systems` if it was in upstream spack).  It being there is a bit hacky, it was done to allow to import it easily with `from spack.pkg.k4.Ilcsoftpackage import ` -- I'll check what the best place to move it is without a complicated setup of another python module.

**Comment by vvolkl** [comment]
Moving the current contents of `packages/Ilcsoftpackage` to the `packages/key4hep-stack` recipe is probably easiest.

**Comment by hegner** [comment]
sounds good to me. Thanks @vvolkl
