### ISSUE TITLE
Current release is hard to use as upstream repository

### ISSUE THREAD

**Issue by tmadlener** [key4hep/key4hep-spack#344]
The latest (i.e. `2022-03-30`) release at `sw.hsf.org` is hard to use as upstream repository, because the `lcg-release` package is present in the `spackages5` directory. When trying to use upstream packages spack goes through all the packages available upstream and the `lcg-release` package lives in the `lcg` repository ([here](https://gitlab.cern.ch/sft/sft-spack-repo.git)).

In order to make this usable as upstream repository users will also have to add the `lcg` repository to their local spack installation.
```sh
git clone https://gitlab.cern.ch/sft/sft-spack-repo.git
spack repo add sft-spack-repo
```

However this is only possible if you have access to that repository (i.e. CERN computing account?) because.

**Comment by vvolkl** [comment]
Yes, this is a bug in spack, in my opinion. Fixed in the key4hep fork: https://github.com/key4hep/spack/commit/403cdc464d17063aba4d060102e04a6b65a3688c

Upstream PR: https://github.com/spack/spack/pull/30063

The sft-spack-repo should have better visibility, but I don't have the permission to change that. I'll ask the repository owner (once they are back from vacation)
