### ISSUE TITLE
CEPCSW has to export LD_LIBRARY_PATH, and install XML files for detectors

### ISSUE THREAD

**Issue by andresailer** [key4hep/key4hep-spack#424]
- OS version: centos7
 - Compiler version: gcc11
 - Package version: /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh
 - Reproduced by: 
      ```
      source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh
      git clone git@github.com:cepc/CEPCSW.git
      cd CEPCSW/Detector/DetCEPCv4/compact
      ddsim --compactFile ./CepC_v4.xml --runType vis
      ```
      This will fail to load the CEPC detector constructor libraries, because the dd4hep plugin manager cannot find the libraries.
      Exporting the LD_LIBRARY_PATH fixes that problem.
      Ideally not having the XMLs on cvmfs would be nice as well
 
Edit: clarified why LD_LIBRARY_PATH is needed (I hope)

**Comment by tmadlener** [comment]
Is the `LD_LIBRARY_PATH` a similar issue as, e.g. https://gitlab.cern.ch/acts/OpenDataDetector/-/merge_requests/41 or is this unrelated?

**Comment by andresailer** [comment]
Here the LD_LIBRARY_PATH has to be set, so that the DD4hep plugin manager finds the plugins.

**Comment by mirguest** [comment]
Hi @andresailer , from the https://github.com/key4hep/key4hep-spack/blob/release/packages/key4hep-stack/package.py#L103, cepcsw is disabled by default. Is that the reason?

**Comment by andresailer** [comment]
Hi @mirguest Maybe that's why there are no LD_LIBRARY_PATHs for it in key4hep setup.sh? But I see daily installed cepcsw packages, so I would be wondering where they come from.

**Comment by andresailer** [comment]
I think the LD_LIBRARY_PATH has to be specified explicitly regardless, but I still wouldn't get it via key4hep/setup.sh if that is added but not part of key4hep-stack

**Comment by vvolkl** [comment]
CEPCSW in principle does set, like all root-dependent packages, set the LD_LIBRARY_PATH in its runtime environment. I think the problem was indeed that it was disabled in the bundle package, and so not part of the setup.sh @mirguest could I ask for a tag of cepcsw? as the last tagged version does not include https://github.com/cepc/CEPCSW/pull/219 which is necessary to be consistent with the latest edm4hep in the stack.

The nightlies indeed still build cepcsw because it is added to the spec list with its git commit hash here https://github.com/key4hep/key4hep-spack/blob/release/scripts/fetch_nightly_versions.py#L105 but it also won't be part of the setup.sh.

**Comment by mirguest** [comment]
Hi @vvolkl , a new release is created for CEPCSW: https://github.com/cepc/CEPCSW/releases/tag/v0.2.6

**Comment by vvolkl** [comment]
Thank you very much for the prompt action! I re-enabled cepcsw now, will check in tomorrow's nightlies and then make a release with it

**Comment by vvolkl** [comment]
Fixed in https://github.com/key4hep/key4hep-spack/pull/425
