### ISSUE TITLE
centos9 build in /cvmfs

### ISSUE THREAD

**Issue by dasphy** [key4hep/key4hep-spack#458]
Hello,
We noticed that there's only centos7 build of key4hep in /cvmfs of lxplus.cern.ch:
[lxplus]$ ls /cvmfs/sw-nightlies.hsf.org/spackages6/key4hep-stack/master-latest/
drwxr-xr-x. 3 cvmfs cvmfs 19 Mar 22 06:31 x86_64-centos7-gcc11.2.0-opt

However, our machine is running Rocky Linux 9 (which should be aligned with centos9).
I am wondering, do we have a build already for running key4hep software on centos9?

Best Regards,
   Tong LI

**Comment by vvolkl** [comment]
Hi Tong Li,

no there is currently no build on centos9. There are plans to add it, but it requires some infrastructure changes to make adding build machines easier. Note that the key4hep-stack uses very few system packages, and as a result the centos7 build is "mainly compatible" with newer distributions. On centos9 you should be able to use the build after installing `glibc-devel` and `libnsl`. The main limitation is that you cannot compile packages that create ROOT dictionaries in this setup.

**Comment by dasphy** [comment]
Hello @vvolkl,
Thanks a lot for your quick reply!
Now on our local server I can make packages compiled except "FCCAnalyses": https://github.com/HEP-FCC/FCCAnalyses
Errors related to ROOT and gcc occurred, here are some lines of them:
104:/cvmfs/sw.hsf.org/spackages6/root/6.26.06/x86_64-centos7-gcc11.2.0-opt/bc7bv/etc//cling/lib/clang/9.0.1/include/wchar.h1::104 :1:error : errorunknown type name '__BEGIN_NAMESPACE_C99':
/cvmfs/sw.hsf.org/spackages6/root/6.26.06/x86_64-centos7-gcc11.2.0-opt/bc7bv/etc//cling/lib/clang/9.0.1/include/wchar.h/cvmfs/sw.hsf.org/spackages6/root/6.26.06/x86_64-centos7-gcc11.2.0-opt/bc7bv/etc//cling/lib/clang/9.0.1/include/wchar.h::106106::2020::  errorerror: : expected ';' after top level declaratorexpected ';' after top level declarator
/cvmfs/sw.hsf.org/contrib/gcc/11.2.0/x86_64-centos7-gcc8.3.0-opt/d3epy/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../include/c++/11.2.0/cstddef:125:5: error: redefinition of 'operator<<'
/cvmfs/sw.hsf.org/contrib/gcc/11.2.0/x86_64-centos7-gcc8.3.0-opt/d3epy/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../include/c++/11.2.0/cstddef:71:42: error: redefinition of '__byte_operand'
(Full info on lxplus.cern.ch: /afs/cern.ch/work/l/lit/public/nicolas/err.log)

For FCC calo simulation, we are using class "CaloNtupleizer" in "FCCAnalyses".
Do we have any idea to solve this problem?

Best,
Tong

**Comment by jmcarcell** [comment]
This is on your Rocky Linux 9 machine, right? I believe I have seen errors like that before when there is something wrong in the setup. By looking at the errors in the file on lxplus it is including headers that come with ROOT instead of using the ones from the gcc folder. 

```
40In file included from :
/cvmfs/sw.hsf.org/contrib/gcc/11.2.0/x86_64-centos7-gcc8.3.0-opt/d3epy/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../include/c++/11.2.0/stringIn file included from :/cvmfs/sw.hsf.org/contrib/gcc/11.2.0/x86_64-centos7-gcc8.3.0-opt/d3epy/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../include/c++/11.2.0/bits/char_traits.h40::
40In file included from :
/cvmfs/sw.hsf.org/contrib/gcc/11.2.0/x86_64-centos7-gcc8.3.0-opt/d3epy/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../include/c++/11.2.0/bits/char_traits.hIn file included from :/cvmfs/sw.hsf.org/contrib/gcc/11.2.0/x86_64-centos7-gcc8.3.0-opt/d3epy/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../include/c++/11.2.0/bits/postypes.h40::
40In file included from :
/cvmfs/sw.hsf.org/contrib/gcc/11.2.0/x86_64-centos7-gcc8.3.0-opt/d3epy/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../include/c++/11.2.0/bits/postypes.hIn file included from :/cvmfs/sw.hsf.org/contrib/gcc/11.2.0/x86_64-centos7-gcc8.3.0-opt/d3epy/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../include/c++/11.2.0/cwchar40::
44In file included from :
/cvmfs/sw.hsf.org/contrib/gcc/11.2.0/x86_64-centos7-gcc8.3.0-opt/d3epy/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../include/c++/11.2.0/cwchar:/cvmfs/sw.hsf.org/spackages6/root/6.26.06/x86_64-centos7-gcc11.2.0-opt/bc7bv/etc//cling/lib/clang/9.0.1/include/wchar.h44::
104:/cvmfs/sw.hsf.org/spackages6/root/6.26.06/x86_64-centos7-gcc11.2.0-opt/bc7bv/etc//cling/lib/clang/9.0.1/include/wchar.h1::104 :1:error : errorunknown type name '__BEGIN_NAMESPACE_C99':
```
So in the fourth line you can see that the ROOT folder starts appearing, but this should not be the case because there is a `wchar.h` in `/cvmfs/sw.hsf.org/contrib/gcc/11.2.0/x86_64-centos7-gcc8.3.0-opt/d3epy/include/c++/11.2.0/tr1`
Since I can't reproduce this, can you tell us exactly what you are doing? It also would be good if you post what you get when you run `env` after sourcing the setup script for the nightlies

**Comment by vvolkl** [comment]
Hi Tong, Juan,

no, this is entirely expected and what I meant with "except for packages building ROOT dictionaries" above. ROOT copies some system headers during its installation and thus breaks the otherwise compatible glibc. At one point we may be able to distribute our own glibc in the stack, but until then, we'll just add a EL9 build once Juan updates the instrastructure.

An immediate workaround is to just do the compilation of ROOT dictionaries in a centos7 docker container, if that's an option for you. You should still be able to use the resulting binaries on rocky.

**Comment by dasphy** [comment]
Hello @vvolkl and @jmcarcell 
Thank you very much for these explanations and suggestions. Yes for the time being a docker container is a good solution, and it's good to see that we have plans to create new build!
Cheers, Tong

**Comment by vvolkl** [comment]
@dasphy no problem. I'll keep this open to keep track of the centos9 build
