### ISSUE TITLE
Deprecate older versions of packages and cleanup packages

### ISSUE THREAD

**Issue by tmadlener** [key4hep/key4hep-spack#476]
Many packages define versions that could be deprecated (and eventually removed) which would allow us to clean up the recipes, e.g. by removing some of the version dependent dependencies.

**Comment by jmcarcell** [comment]
I did some cleanup in https://github.com/key4hep/key4hep-spack/commit/877a7d94f2bd563e00482c3da2dc1f88eb1626aa and https://github.com/key4hep/key4hep-spack/commit/ae4b8bfcef473ff1c2a69b1c174e32887191383d (maybe it's better to check a diff in case I'm missing a commit) based, more or less, on the date so most versions removed are from the previous decade. It's unlikely someone wants to build them and also it's unlikely it will work without changes since they will pick up the latest versions of the dependencies in most cases. There are still many old versions but those were enough changes for the last round
