### ISSUE TITLE
Remove old nightly builds in gitlab workflow

### ISSUE THREAD

**Issue by vvolkl** [key4hep/key4hep-spack#482]
sw-nightlies.hsf.org was nearing its quota of 50 GB on cvmfs. The quota has been doubled so there is no urgency, but there is also no reason to keep old nightly builds indefinitely. A schedule could be added to the .gitlab-ci.yaml to regularly remove old nightly builds.

**Comment by jmcarcell** [comment]
Now there is a workflow to delete old nightlies which has been tested and used: https://gitlab.cern.ch/key4hep/k4-deploy/-/blob/release/.gitlab-ci.yml#L417
There was a bigger problem with the quota (now 200 GB) because the cvmfs parameters were making garbage collection happen very infrequently and they would preserve many revisions, so it would take a very long time until for the files to actually be deleted. They were changed and now garbage collection happens often and keeps few revisions, so we are typically at around 50 GB or less.
