### ISSUE TITLE
System glibc and libnsl

### ISSUE THREAD

**Issue by kjvbrt** [key4hep/key4hep-spack#530]
Hi, 

In FCCDetectors mirror on CERN's GitLab jobs fails with:
```
-- Check for working C compiler: /cvmfs/sw.hsf.org/contrib/gcc/11.2.0/x86_64-centos7-gcc8.3.0-opt/d3epy/bin/gcc
-- Check for working C compiler: /cvmfs/sw.hsf.org/contrib/gcc/11.2.0/x86_64-centos7-gcc8.3.0-opt/d3epy/bin/gcc - broken
CMake Error at /cvmfs/sw.hsf.org/spackages7/cmake/3.25.2/x86_64-centos7-gcc11.2.0-opt/c4tzf/share/cmake-3.25/Modules/CMakeTestCCompiler.cmake:70 (message):
  The C compiler
    "/cvmfs/sw.hsf.org/contrib/gcc/11.2.0/x86_64-centos7-gcc8.3.0-opt/d3epy/bin/gcc"
  is not able to compile a simple test program.
  It fails with the following output:
    Change Dir: /builds/hep-fcc/FCCDetectors/build/CMakeFiles/CMakeScratch/TryCompile-Pnr76d
    
    Run Build Command(s):/cvmfs/sw.hsf.org/spackages7/ninja/1.11.1/x86_64-centos7-gcc11.2.0-opt/rb5re/bin/ninja-build cmTC_3cff3 && [1/2] Building C object CMakeFiles/cmTC_3cff3.dir/testCCompiler.c.o
    [2/2] Linking C executable cmTC_3cff3
    FAILED: cmTC_3cff3 
    : && /cvmfs/sw.hsf.org/contrib/gcc/11.2.0/x86_64-centos7-gcc8.3.0-opt/d3epy/bin/gcc   CMakeFiles/cmTC_3cff3.dir/testCCompiler.c.o -o cmTC_3cff3   && :
    /cvmfs/sw.hsf.org/contrib/binutils/2.38/x86_64-centos7-gcc8.3.0-opt/pv4x2/bin/ld: cannot find crt1.o: No such file or directory
    /cvmfs/sw.hsf.org/contrib/binutils/2.38/x86_64-centos7-gcc8.3.0-opt/pv4x2/bin/ld: cannot find crti.o: No such file or directory
    collect2: error: ld returned 1 exit status
    ninja: build stopped: subcommand failed.
```
[link](https://gitlab.cern.ch/hep-fcc/FCCDetectors/-/jobs/32385075)

the solution I found is to install `glibc-devel` package, but shouldn't those files be provided from the key4hep stack, with package `glibc`?

Also, when linking, `libnsl` is missing.

 - OS version: AlmaLinuix9
 - Compiler version: GCC 11.2.0
 - Key4hep stack: stable
 - Package version: https://gitlab.cern.ch/hep-fcc/FCCDetectors
 - Reproduced by: Running installation of FCCDetectors in GitLab runner with cvmfs

**Comment by jmcarcell** [comment]
So the image is AlmaLinux9 right? And then the workflow is sourcing the releases so what's happening is that for Alma9 we don't ship any compilers since the ones that come in Alma9 are relatively recent and then this is trying to use the Centos 7 and having some issues because the Alma9 image that you are using doesn't have gcc installed. Some of the options are using the image that is used to build in key4hep: `gitlab-registry.cern.ch/key4hep/k4-deploy/alma9-build` ([Dockerfile](https://github.com/key4hep/key4hep-images/blob/main/Docker/alma9-build/Dockerfile)) or installing what's missing in the image as you did. 

I think there is nothing more to be done for this issue; the summary is that for an image that doesn't have `gcc` and other development tools installed it won't work for Ubuntu and Alma9 since we don't ship compilers nor glibc or other libraries. At some point we'll have to ship compilers also with Ubuntu and Alma9. I'll add some information about this in the README of https://github.com/key4hep/key4hep-spack.
