### ISSUE TITLE
Pythia8 not built agains HepMC3

### ISSUE THREAD

**Issue by dirkzerwas** [key4hep/key4hep-spack#608]
Hi @jmcarcell,
after discussion with the MCGenerator authors, adding pythia8 to the k4GeneratorsConfiguration worked only partially:
- compiles and runs
- but the hepmc3 plugin does not seem to be availlable to write hepmc3 output . Adding the Sjostrand recipe of main144, the primary include file "Pythia8Plugins/HepMC3.h" exists, but then the proper "HepMC3::GenEvent.h" etc cannot be found. It looks kind of like pythia8 was compiled/installed without the HepMC3 package
Cheers,
Dirk

**Comment by tmadlener** [comment]
The fact that pythia8 is not compiled with hepmc3 support can also be verified with
```console
$ pythia8-config --with-hepmc3
false
```

Just to add a bit more spack information here, we also just tried to do the following (locally in my stack):

```yaml
pythia8:
  require: "+gzip +hempc3"
```
and we ran into a (non-descriptive) concretization error. It was not immediately clear to me where this conflict comes from. At least simply grepping for `"pythia8"` in spack and key4hep-spack doesn't yield any obvious conflict. However, something must require `pythia8~hepmc3`, because by default the `hepmc3` variant is on in pythia8.

**Comment by jmcarcell** [comment]
Let's see tomorrow with #611, see the explanation there.

**Comment by jmcarcell** [comment]
It seems to be fine now

**Comment by dirkzerwas** [comment]
Checked: compiled and ran without a hitch, thanks!
