### ISSUE TITLE
Add k4GeneratorsConfig package and include it in key4hep-stack

### ISSUE THREAD

**Issue by tmadlener** [key4hep/key4hep-spack#617]
Just to not forget about this.

@dirkzerwas FYI

**Comment by BrieucF** [comment]
Hi,

First, congrats on the initiative, this will be extremely useful to many!

I'd like to re-open this issue because:
- the `K4GENERATORSCONFIG` environment variables points to a non-existant path (looks like k4geo is somehow appended?) 
- the comment in `package.py` says "DD4hep geometry models for future colliders." (see https://github.com/key4hep/key4hep-spack/blob/main/packages/k4generatorsconfig/package.py)
- I would like to know how to get the executable from the Key4hep environment, do we define something similar to `k4gen="python3 ${K4GenDir}/python/main.py"` ? (but maybe with another name than k4gen which is another repository included Key4hep) 
- maybe we could also make the examples available from `$K4GENERATORSCONFIG`?

**Comment by dirkzerwas** [comment]
Hi @BrieucF!
thank you @jmcarcell for the implementation!

Maybe this line:
env.set("K4GENERATORSCONFIG", self.prefix.share.k4geo)
should rather be:
env.set("K4GENERATORSCONFIG", self.prefix.share.k4generatorsconfig)
though I do not know if and where self.prefix.share.k4generatorsconfig is set?

For the executable (@apricePhy): we can change the alias k4gen to k4configureGenerators (or something else) to avoid confusion.

Can spack run the "source setup.sh" in k4GeneratorsConfig, then you would have the alias?

**Comment by tmadlener** [comment]
Looking into things a bit, I found the following:
- k4GeneratorsConfig doesn't yet have anything in a `share` directory. Hence, the ususal place that we use to set this variable to doesn't exist. Should we set it to something else, e.g. simply the install prefix?
- For getting a `k4gen` (or similar) executable, it is probably easiest to do the necessary things in k4GeneratorsConfig directly. I.e. I would make `python/main.py` executable and then create a symlink with the expected name in `<prefix>/bin` during installation.

> Can spack run the "source setup.sh" in k4GeneratorsConfig, then you would have the alias?

Not easily, but we can do everything that is done there in the `package.py`

**Comment by dirkzerwas** [comment]
ok: the alias is updated.

- I am happy to remove setup.* if this can go to package.py
- I can add "share" to the package, will have a look....

**Comment by tmadlener** [comment]
> I am happy to remove setup.* if this can go to package.py

We can just have both. Having a `setup.sh` usually makes it a bit easier to setup an environment for a local installation.

**Comment by dirkzerwas** [comment]
share added and CMakeList.txt updated to install it , thanks @tmadlener

**Comment by BrieucF** [comment]
Thanks!
