### ISSUE TITLE
LLVM and Gaudi conflict

### ISSUE THREAD

**Issue by joequant** [key4hep/key4hep-spack#83]
LLVM 11 needs python 3.8 but Gaudi needs 3.7

Is there any way to fix package.yaml so that it builds both?

**Comment by tmadlener** [comment]
Hi @joequant,
I am afraid, that unless LLVM 11 also supports python 3.7, or Gaudi starts to work with python 3.8, this is a genuine conflict in the requirements that cannot be easily fixed by tweaking the `packages.yaml` config.

As a workaround, it might be possible to build LLVM with python 3.8 and then build a second python 3.7 that is used by Gaudi, but I don't know if you are then able to setup a consistent runtime environment using these.

**Comment by vvolkl** [comment]
Hi @joequant,

yes, adding to Thomas, `gaudi@develop` should work with python 3.8, but the branch it points to has changed a bit since I added this version - fixing this now.

**Comment by joequant** [comment]
It turns out that there is nice feature of packages.yaml that fixes the issue.  Packages.yaml allows for multiple versions so that inserting a line to make to build both 3.7.8 and 3.8.6 works.

  # gaudi v34 does not work with python 3.8
  # setting the version explicitly avoids concretizer errors
  python:
    version: [3.7.8, 3.8.6]

**Comment by vvolkl** [comment]
Interesting, thanks for sharing! Another alternative: build `llvm~python`?

**Comment by joequant** [comment]
Don't know what the implications of that are.  

But I'm pretty impressed with spack and the multi-versioning.  It's not necessary clear what magic strings you need to get a good build, but there's always at least a good set of strings.
